web_dir: '/'
upload_dir: '/upload/'
tmp_dir: '/tmp/'

kid:
  name: Pamplemousse
  baseline: "Née le <strong>29 septembre 2015</strong>"
  pregnancydate: 13-02-2015
  birthdate: 29-09-2015


database:
  dbname: pamplemousse
  user: root
  password: root
  host: localhost
  driver: 'pdo_mysql'

thumbnails:
  dir: '/thumbnail/'
  size:
    - 200x200
    - 800x800
    - 1200x

users:
  admin:
    - ROLE_ADMIN
    # raw password is foo
    - 5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg==
