web_dir: '/'
upload_dir: '/upload/'
thumbnail_dir: '/thumbnail/'

kid:
  name: Pamplemousse
  baseline: "Mise en production prévu <strong>fin mars 2016</strong>"
  birthdate: 26/06/2016

database:
  dbname: pamplemousse
  user: root
  password: root
  host: localhost
  driver: 'pdo_mysql'
